name: bptsb
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10.4
  - pytorch==1.11.0
  - yaml==0.2.5
  - pip
  - pip:
    - torchvision==0.23.0
    - pyyaml==6.0
    - matplotlib==3.5.1
    - numpy==1.22.3
    - pandas==1.5.3
    - scikit-learn==1.3.0
    - scipy==1.9.1